package com.tyut.vo;

import java.sql.Date;

public class GirthVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girth.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girth.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girth.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girth.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girth.id
     *
     * @return the value of girth.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girth.id
     *
     * @param id the value for girth.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girth.type
     *
     * @return the value of girth.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girth.type
     *
     * @param type the value for girth.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girth.value
     *
     * @return the value of girth.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girth.value
     *
     * @param value the value for girth.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girth.create_time
     *
     * @return the value of girth.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girth.create_time
     *
     * @param createTime the value for girth.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }
}
