package com.tyut.vo;

import java.io.Serializable;

public class MSchema implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.mainpic
     *
     * @mbg.generated
     */
    private String mainpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.jrpic
     *
     * @mbg.generated
     */
    private String jrpic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.execute_index
     *
     * @mbg.generated
     */
    private String executeIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.health_index
     *
     * @mbg.generated
     */
    private String healthIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.cost_index
     *
     * @mbg.generated
     */
    private String costIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.carbs
     *
     * @mbg.generated
     */
    private Integer carbs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.protein
     *
     * @mbg.generated
     */
    private Integer protein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.fat
     *
     * @mbg.generated
     */
    private Integer fat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mschema.calories
     *
     * @mbg.generated
     */
    private Integer calories;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.id
     *
     * @return the value of mschema.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.id
     *
     * @param id the value for mschema.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.userid
     *
     * @return the value of mschema.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.userid
     *
     * @param userid the value for mschema.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.name
     *
     * @return the value of mschema.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.name
     *
     * @param name the value for mschema.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.intro
     *
     * @return the value of mschema.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.intro
     *
     * @param intro the value for mschema.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.content
     *
     * @return the value of mschema.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.content
     *
     * @param content the value for mschema.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.mainpic
     *
     * @return the value of mschema.mainpic
     *
     * @mbg.generated
     */
    public String getMainpic() {
        return mainpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.mainpic
     *
     * @param mainpic the value for mschema.mainpic
     *
     * @mbg.generated
     */
    public void setMainpic(String mainpic) {
        this.mainpic = mainpic == null ? null : mainpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.jrpic
     *
     * @return the value of mschema.jrpic
     *
     * @mbg.generated
     */
    public String getJrpic() {
        return jrpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.jrpic
     *
     * @param jrpic the value for mschema.jrpic
     *
     * @mbg.generated
     */
    public void setJrpic(String jrpic) {
        this.jrpic = jrpic == null ? null : jrpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.execute_index
     *
     * @return the value of mschema.execute_index
     *
     * @mbg.generated
     */
    public String getExecuteIndex() {
        return executeIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.execute_index
     *
     * @param executeIndex the value for mschema.execute_index
     *
     * @mbg.generated
     */
    public void setExecuteIndex(String executeIndex) {
        this.executeIndex = executeIndex == null ? null : executeIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.health_index
     *
     * @return the value of mschema.health_index
     *
     * @mbg.generated
     */
    public String getHealthIndex() {
        return healthIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.health_index
     *
     * @param healthIndex the value for mschema.health_index
     *
     * @mbg.generated
     */
    public void setHealthIndex(String healthIndex) {
        this.healthIndex = healthIndex == null ? null : healthIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.cost_index
     *
     * @return the value of mschema.cost_index
     *
     * @mbg.generated
     */
    public String getCostIndex() {
        return costIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.cost_index
     *
     * @param costIndex the value for mschema.cost_index
     *
     * @mbg.generated
     */
    public void setCostIndex(String costIndex) {
        this.costIndex = costIndex == null ? null : costIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.carbs
     *
     * @return the value of mschema.carbs
     *
     * @mbg.generated
     */
    public Integer getCarbs() {
        return carbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.carbs
     *
     * @param carbs the value for mschema.carbs
     *
     * @mbg.generated
     */
    public void setCarbs(Integer carbs) {
        this.carbs = carbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.protein
     *
     * @return the value of mschema.protein
     *
     * @mbg.generated
     */
    public Integer getProtein() {
        return protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.protein
     *
     * @param protein the value for mschema.protein
     *
     * @mbg.generated
     */
    public void setProtein(Integer protein) {
        this.protein = protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.fat
     *
     * @return the value of mschema.fat
     *
     * @mbg.generated
     */
    public Integer getFat() {
        return fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.fat
     *
     * @param fat the value for mschema.fat
     *
     * @mbg.generated
     */
    public void setFat(Integer fat) {
        this.fat = fat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mschema.calories
     *
     * @return the value of mschema.calories
     *
     * @mbg.generated
     */
    public Integer getCalories() {
        return calories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mschema.calories
     *
     * @param calories the value for mschema.calories
     *
     * @mbg.generated
     */
    public void setCalories(Integer calories) {
        this.calories = calories;
    }
}