package com.tyut.vo;

import java.util.Date;

public class Mysport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mysport.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mysport.sportid
     *
     * @mbg.generated
     */
    private Integer sportid;
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mysport.time
     *
     * @mbg.generated
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mysport.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mysport.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mysport.id
     *
     * @return the value of mysport.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mysport.id
     *
     * @param id the value for mysport.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mysport.sportid
     *
     * @return the value of mysport.sportid
     *
     * @mbg.generated
     */
    public Integer getSportid() {
        return sportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mysport.sportid
     *
     * @param sportid the value for mysport.sportid
     *
     * @mbg.generated
     */
    public void setSportid(Integer sportid) {
        this.sportid = sportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mysport.time
     *
     * @return the value of mysport.time
     *
     * @mbg.generated
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mysport.time
     *
     * @param time the value for mysport.time
     *
     * @mbg.generated
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mysport.create_time
     *
     * @return the value of mysport.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mysport.create_time
     *
     * @param createTime the value for mysport.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mysport.update_time
     *
     * @return the value of mysport.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mysport.update_time
     *
     * @param updateTime the value for mysport.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    @Override
    public String toString() {
        return "Mysport{" +
                "id=" + id +
                ", sportid=" + sportid +
                ", userid=" + userid +
                ", time=" + time +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }
}