package com.tyut.vo;


import java.sql.Date;

public class Punchin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punchin.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column punchin.createtime
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punchin.userid
     *
     * @return the value of punchin.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punchin.userid
     *
     * @param userid the value for punchin.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column punchin.createtime
     *
     * @return the value of punchin.createtime
     *
     * @mbg.generated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column punchin.createtime
     *
     * @param createtime the value for punchin.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }
}