package com.tyut.vo;

public class UserVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userpic
     *
     * @mbg.generated
     */
    private String userpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.height
     *
     * @mbg.generated
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weight
     *
     * @mbg.generated
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.activitystatus
     *
     * @mbg.generated
     */
    private Integer activitystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.schemaid
     *
     * @mbg.generated
     */
    private Integer schemaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_user.create_time
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column neuedu_user.update_time
     *
     * @mbg.generated
     */
    private String updatetime;

    private Integer goal;

    private String initialweight;

    private Boolean ifFollow;

    private Integer topacid;

    public Integer getTopacid() {
        return topacid;
    }

    public void setTopacid(Integer topacid) {
        this.topacid = topacid;
    }

    public Boolean getIfFollow() {
        return ifFollow;
    }

    public void setIfFollow(Boolean ifFollow) {
        this.ifFollow = ifFollow;
    }

    public String getInitialweight() {
        return initialweight;
    }

    public void setInitialweight(String initialweight) {
        this.initialweight = initialweight;
    }

    public Integer getGoal() {
        return goal;
    }

    public void setGoal(Integer goal) {
        this.goal = goal;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getUserpic() {
        return userpic;
    }

    public void setUserpic(String userpic) {
        this.userpic = userpic;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getHeight() {
        return height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getActivitystatus() {
        return activitystatus;
    }

    public void setActivitystatus(Integer activitystatus) {
        this.activitystatus = activitystatus;
    }

    public Integer getSchemaid() {
        return schemaid;
    }

    public void setSchemaid(Integer schemaid) {
        this.schemaid = schemaid;
    }

    public String getCreatetime() {
        return createtime;
    }

    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    public String getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }
}